import Link from 'next/link';
import { ArrowRight, Compass } from 'lucide-react';
import SiteHeader from '../components/site-header';
import SiteFooter from '../components/site-footer';
import { routes } from '../lib/routes';

const cards = [
  ['Cairo','Egypt · History and design','https://images.unsplash.com/photo-1503177119275-0aa32b3a9368?auto=format&fit=crop&w=1200&q=90','large'],
  ['Luxor','Egypt · Ancient stories','https://images.unsplash.com/photo-1568322445389-f64ac2515020?auto=format&fit=crop&w=900&q=90','small'],
  ['Sharm El Sheikh','Egypt · Reefs and resorts','https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=900&q=90','small'],
  ['Siwa Oasis','Egypt · Palms and springs','https://images.unsplash.com/photo-1544986581-efac024faf62?auto=format&fit=crop&w=900&q=90','wide'],
];
export default function DestinationsPage() { return <main className="destinations-page"><SiteHeader section="trip"/><section className="destinations-intro"><div><span className="eyebrow">CURATED EGYPT DESTINATIONS</span><h1>Go somewhere<br/><em>beautiful.</em></h1><p>From Nile mornings to Red Sea light, discover Egyptian places selected for the feeling they leave behind.</p><Link href={routes.search('trip')} className="primary-cta">Explore all places <ArrowRight size={15}/></Link></div><div className="compass-art"><Compass size={92}/><span>Find your<br/>north</span></div></section><section className="destination-editorial"><div className="editorial-heading"><div><span className="eyebrow">EGYPT, CURATED</span><h2>Where will you<br/><em>go next?</em></h2></div><p>Every destination has a different rhythm. Choose the Egyptian route that feels like yours.</p></div><div className="destination-mosaic">{cards.map(([name,country,image,size]) => <Link href={`${routes.search('trip')}&location=${encodeURIComponent(name)}`} className={`mosaic-card ${size}`} key={name} style={{backgroundImage:`linear-gradient(0deg,rgba(3,18,31,.86),rgba(3,18,31,.04) 70%),url(${image})`}}><span><strong>{name}</strong><small>{country}</small></span><ArrowRight size={17}/></Link>)}</div></section><section className="destination-discovery"><div><span className="eyebrow">TRAVEL BY FEELING</span><h2>Start with a feeling.</h2><p>Whether you want to slow down, dive, wander, or taste something new, there is an Egyptian route waiting for you.</p></div><div className="feeling-pills"><Link href={`${routes.search('trip')}&type=Family%20trips`}>Quiet mornings</Link><Link href={`${routes.search('trip')}&type=Beach%20%26%20diving`}>Sea & sunshine</Link><Link href={`${routes.search('trip')}&type=Temples%20%26%20history`}>Culture & stories</Link><Link href={`${routes.search('trip')}&type=Adventure`}>Mountain air</Link></div></section><SiteFooter section="trip"/></main>; }
