'use client';

import Link from 'next/link';
import { ArrowRight, CalendarDays, Check, CheckCircle2, ChevronLeft, Compass, Hotel, MapPin, Minus, Plane, Plus, Send, ShieldCheck, Sparkles, Users, Wallet } from 'lucide-react';
import { useMemo, useState } from 'react';
import SiteFooter from '../components/site-footer';
import SiteHeader from '../components/site-header';

type TripPlan = { destination: string; startDate: string; endDate: string; travelers: number; style: string; pace: string; budget: string; interests: string[]; stay: string; transport: string; notes: string };
const destinations = [['Cairo', 'Museums, markets, and city energy', 'https://images.unsplash.com/photo-1568322445389-f64ac2515020?auto=format&fit=crop&w=700&q=88'], ['Luxor & Aswan', 'Temples, tombs, and Nile mornings', 'https://images.unsplash.com/photo-1539650116574-75c0c6d73f6e?auto=format&fit=crop&w=700&q=88'], ['Red Sea', 'Reefs, beaches, and easy-going days', 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=700&q=88'], ['Siwa & the desert', 'Oases, stars, and slower rhythms', 'https://images.unsplash.com/photo-1544986581-efac024faf62?auto=format&fit=crop&w=700&q=88']];
const styles = ['History & culture', 'Nile cruise', 'Beach escape', 'Adventure', 'Food & local life', 'Luxury retreat'];
const paces = ['Slow & spacious', 'Balanced', 'Full days'];
const budgets = ['Comfort', 'Premium', 'Luxury'];
const interests = ['Ancient sites', 'Local food', 'Photography', 'Nature & water', 'Wellness', 'Shopping', 'Family time', 'Nightlife'];
const stays = ['Boutique hotels', 'Resorts', 'Nile cruise cabins', 'Private villas', 'A mix of stays'];
const transports = ['Private transfers', 'Driver and guide', 'Domestic flights', 'Train and local transfers'];
const initialPlan: TripPlan = { destination: '', startDate: '', endDate: '', travelers: 2, style: '', pace: 'Balanced', budget: 'Premium', interests: [], stay: 'A mix of stays', transport: 'Private transfers', notes: '' };

export default function TailorYourTripPage() {
  const [step, setStep] = useState(1); const [plan, setPlan] = useState<TripPlan>(initialPlan); const [submitted, setSubmitted] = useState(false); const totalSteps = 5;
  const update = <K extends keyof TripPlan>(key: K, value: TripPlan[K]) => setPlan((current) => ({ ...current, [key]: value }));
  const toggleInterest = (interest: string) => update('interests', plan.interests.includes(interest) ? plan.interests.filter((item) => item !== interest) : [...plan.interests, interest]);
  const canContinue = step === 1 ? Boolean(plan.destination) : step === 2 ? Boolean(plan.startDate && plan.endDate) : step === 3 ? Boolean(plan.style) : true;
  const tripLength = useMemo(() => { if (!plan.startDate || !plan.endDate) return 'Dates to be confirmed'; const days = Math.max(1, Math.round((new Date(plan.endDate).getTime() - new Date(plan.startDate).getTime()) / 86400000)); return `${days} ${days === 1 ? 'day' : 'days'}`; }, [plan.startDate, plan.endDate]);
  return <main className="trip-builder-page"><SiteHeader section="trip"/><section className="trip-builder-hero"><span className="travel-studio-kicker"><Sparkles size={14}/> YOUR JOURNEY, YOUR WAY</span><h1>Build a trip that<br/><em>feels like yours.</em></h1><p>Start with a blank page. We’ll help you shape the places, pace, and details into a considered Egypt itinerary.</p><div className="trip-builder-hero-meta"><span><CheckCircle2 size={15}/>No commitment</span><span><Compass size={15}/>Local trip planners</span><span><ShieldCheck size={15}/>Flexible options</span></div></section><section className="trip-builder-shell">{submitted ? <SuccessPlan plan={plan} tripLength={tripLength} onEdit={() => setSubmitted(false)}/> : <><div className="trip-builder-top"><div><span className="eyebrow">TRIP DESIGNER</span><h2>Let’s shape your route.</h2></div><span className="trip-builder-step-count">STEP {step} OF {totalSteps}</span></div><div className="trip-builder-progress"><span className="trip-builder-progress-line" style={{ width: `${((step - 1) / (totalSteps - 1)) * 100}%` }}/>{['Where', 'When', 'Style', 'Details', 'Review'].map((label, index) => <button type="button" key={label} className={step >= index + 1 ? 'active' : ''} onClick={() => index + 1 < step && setStep(index + 1)}><i>{index + 1 < step ? <Check size={13}/> : index + 1}</i><small>{label}</small></button>)}</div><div className="trip-builder-grid"><div className="trip-builder-form">{step === 1 && <StepDestination value={plan.destination} onChange={(value) => update('destination', value)}/>} {step === 2 && <StepDates plan={plan} update={update}/>} {step === 3 && <StepStyle plan={plan} update={update}/>} {step === 4 && <StepDetails plan={plan} update={update} toggleInterest={toggleInterest}/>} {step === 5 && <StepReview plan={plan} tripLength={tripLength}/>}<div className="trip-builder-actions">{step > 1 && <button type="button" className="trip-builder-back" onClick={() => setStep((current) => current - 1)}><ChevronLeft size={16}/> Back</button>}{step < totalSteps ? <button type="button" className="primary-cta" disabled={!canContinue} onClick={() => setStep((current) => current + 1)}>Continue <ArrowRight size={16}/></button> : <button type="button" className="primary-cta" onClick={() => setSubmitted(true)}><Send size={15}/> Create my trip brief</button>}</div></div><TripSummary plan={plan} tripLength={tripLength}/></div></>}</section><section className="trip-builder-reassurance"><div><ShieldCheck size={21}/><strong>Your details stay private</strong><p>We only use your trip brief to prepare a better recommendation.</p></div><div><Users size={21}/><strong>A real person reviews it</strong><p>A Montu Travel planner will help turn your choices into a route.</p></div><Link href="/travel" className="travel-studio-outline">Need inspiration first <ArrowRight size={15}/></Link></section><SiteFooter section="trip"/></main>;
}

function StepDestination({ value, onChange }: { value: string; onChange: (value: string) => void }) { return <div className="trip-builder-step"><span className="eyebrow">STEP 01 · WHERE</span><h3>Where do you want to go?</h3><p>Choose a starting point. You can combine destinations later.</p><div className="trip-destination-options">{destinations.map(([name, text, image]) => <button type="button" key={name} className={value === name ? 'selected' : ''} onClick={() => onChange(name)} style={{ backgroundImage: `linear-gradient(0deg,rgba(3,18,31,.9),rgba(3,18,31,.05)),url(${image})` }}><span><strong>{name}</strong><small>{text}</small></span>{value === name && <CheckCircle2 size={18}/>}</button>)}</div></div>; }
function StepDates({ plan, update }: { plan: TripPlan; update: <K extends keyof TripPlan>(key: K, value: TripPlan[K]) => void }) { return <div className="trip-builder-step"><span className="eyebrow">STEP 02 · WHEN</span><h3>When would you like to travel?</h3><p>Give us a rough window. We can refine the route around availability and season.</p><div className="trip-date-fields"><label><CalendarDays size={17}/>Start date<input type="date" value={plan.startDate} onChange={(event) => update('startDate', event.target.value)}/></label><label><CalendarDays size={17}/>End date<input type="date" value={plan.endDate} min={plan.startDate} onChange={(event) => update('endDate', event.target.value)}/></label></div><div className="trip-travelers-control"><div><Users size={19}/><span><strong>Travelers</strong><small>How many people are joining?</small></span></div><div><button type="button" aria-label="Remove traveler" onClick={() => update('travelers', Math.max(1, plan.travelers - 1))}><Minus size={15}/></button><strong>{plan.travelers}</strong><button type="button" aria-label="Add traveler" onClick={() => update('travelers', Math.min(20, plan.travelers + 1))}><Plus size={15}/></button></div></div></div>; }
function StepStyle({ plan, update }: { plan: TripPlan; update: <K extends keyof TripPlan>(key: K, value: TripPlan[K]) => void }) { return <div className="trip-builder-step"><span className="eyebrow">STEP 03 · STYLE</span><h3>What should the trip feel like?</h3><p>Pick the closest match. Your planner can blend several styles into one route.</p><h4>Trip style</h4><div className="trip-choice-grid">{styles.map((style) => <button type="button" key={style} className={plan.style === style ? 'selected' : ''} onClick={() => update('style', style)}>{plan.style === style && <Check size={14}/>} {style}</button>)}</div><h4>Daily pace</h4><div className="trip-choice-grid trip-choice-grid-three">{paces.map((pace) => <button type="button" key={pace} className={plan.pace === pace ? 'selected' : ''} onClick={() => update('pace', pace)}>{plan.pace === pace && <Check size={14}/>} {pace}</button>)}</div></div>; }
function StepDetails({ plan, update, toggleInterest }: { plan: TripPlan; update: <K extends keyof TripPlan>(key: K, value: TripPlan[K]) => void; toggleInterest: (value: string) => void }) { return <div className="trip-builder-step"><span className="eyebrow">STEP 04 · DETAILS</span><h3>Make it personal.</h3><p>These details help us recommend the right experiences, stays, and practical rhythm.</p><h4>Budget level</h4><div className="trip-choice-grid trip-choice-grid-three">{budgets.map((budget) => <button type="button" key={budget} className={plan.budget === budget ? 'selected' : ''} onClick={() => update('budget', budget)}><Wallet size={14}/>{budget}</button>)}</div><h4>Interests</h4><div className="trip-choice-grid">{interests.map((interest) => <button type="button" key={interest} className={plan.interests.includes(interest) ? 'selected' : ''} onClick={() => toggleInterest(interest)}>{plan.interests.includes(interest) && <Check size={14}/>} {interest}</button>)}</div><div className="trip-detail-selects"><label>Preferred stay<select value={plan.stay} onChange={(event) => update('stay', event.target.value)}>{stays.map((stay) => <option key={stay}>{stay}</option>)}</select></label><label>Getting around<select value={plan.transport} onChange={(event) => update('transport', event.target.value)}>{transports.map((transport) => <option key={transport}>{transport}</option>)}</select></label></div><label className="trip-notes-label">Anything else we should know?<textarea value={plan.notes} onChange={(event) => update('notes', event.target.value)} rows={4} placeholder="A celebration, accessibility needs, a must-see place, or anything that matters to you..."/></label></div>; }
function StepReview({ plan, tripLength }: { plan: TripPlan; tripLength: string }) { return <div className="trip-builder-step"><span className="eyebrow">STEP 05 · REVIEW</span><h3>Your trip brief is ready.</h3><p>Review your choices. You can go back and adjust anything before creating the brief.</p><div className="trip-review-grid"><ReviewItem icon={<MapPin size={16}/>} label="Destination" value={plan.destination}/><ReviewItem icon={<CalendarDays size={16}/>} label="Dates" value={`${tripLength}${plan.startDate ? ` · ${plan.startDate}` : ''}`}/><ReviewItem icon={<Compass size={16}/>} label="Style" value={`${plan.style} · ${plan.pace}`}/><ReviewItem icon={<Users size={16}/>} label="Travelers" value={`${plan.travelers} people`}/><ReviewItem icon={<Hotel size={16}/>} label="Stay" value={plan.stay}/><ReviewItem icon={<Plane size={16}/>} label="Transport" value={plan.transport}/></div><div className="trip-review-note"><Sparkles size={18}/><span>Next, a Montu Travel planner will use this brief to suggest a route, stays, and experiences that fit.</span></div></div>; }
function ReviewItem({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) { return <div><span>{icon}<small>{label}</small></span><strong>{value || 'Not selected'}</strong></div>; }
function TripSummary({ plan, tripLength }: { plan: TripPlan; tripLength: string }) { return <aside className="trip-live-summary"><span className="eyebrow">YOUR TRIP BRIEF</span><div className="trip-summary-image"/><h3>{plan.destination || 'Your Egypt journey'}</h3><p>{plan.style || 'Choose a travel style'} · {plan.travelers} travelers</p><div className="trip-summary-divider"/><span><CalendarDays size={15}/>{tripLength}</span><span><Hotel size={15}/>{plan.stay}</span><span><Wallet size={15}/>{plan.budget} budget</span>{plan.interests.length > 0 && <div className="trip-summary-tags">{plan.interests.slice(0, 3).map((interest) => <small key={interest}>{interest}</small>)}</div>}<small className="trip-summary-note">Your selections update as you build.</small></aside>; }
function SuccessPlan({ plan, tripLength, onEdit }: { plan: TripPlan; tripLength: string; onEdit: () => void }) { const message = `Hello Montu Travel, I would like to plan a trip. Destination: ${plan.destination || 'To be decided'}. Dates: ${tripLength}${plan.startDate ? ` (${plan.startDate} to ${plan.endDate})` : ''}. Travelers: ${plan.travelers}. Style: ${plan.style || 'To be decided'}. Pace: ${plan.pace}. Budget: ${plan.budget}. Interests: ${plan.interests.join(', ') || 'To be decided'}. Stay: ${plan.stay}. Transport: ${plan.transport}. Notes: ${plan.notes || 'None'}`; const whatsappHref = `https://wa.me/201038822537?text=${encodeURIComponent(message)}`; return <div className="trip-success"><div className="trip-success-icon"><Check size={28}/></div><span className="eyebrow">YOUR TRIP BRIEF IS READY</span><h2>{plan.destination || 'Your Egypt journey'} is taking shape.</h2><p>We’ve captured your preferences for a {tripLength.toLowerCase()} {plan.style.toLowerCase() || 'Egypt'} trip for {plan.travelers} travelers. Send this brief to a Montu Travel planner on WhatsApp and refine the details together.</p><div className="trip-success-actions"><a href={whatsappHref} target="_blank" rel="noreferrer" className="primary-cta">Send brief on WhatsApp <ArrowRight size={15}/></a><button type="button" className="trip-builder-back" onClick={onEdit}>Edit my brief</button></div></div>; }
