'use client';
import { CalendarCheck, Heart, MessageCircle, X } from 'lucide-react';
import { useState } from 'react';

export default function BookingActions({ propertyId, propertyTitle }: { propertyId: string; propertyTitle: string }) {
  const [mode, setMode] = useState<'booking' | 'contact' | null>(null);
  const [sent, setSent] = useState(false);
  const [saved, setSaved] = useState(() => typeof window !== 'undefined' && JSON.parse(window.localStorage.getItem('al-aroum-favorites') || '[]').includes(propertyId));
  const toggleSaved = () => { const list: string[] = JSON.parse(window.localStorage.getItem('al-aroum-favorites') || '[]'); const next = list.includes(propertyId) ? list.filter((id) => id !== propertyId) : [...list, propertyId]; window.localStorage.setItem('al-aroum-favorites', JSON.stringify(next)); setSaved(!saved); };
  return <><div className="mt-6 grid gap-3"><button className="gradient-button flex items-center justify-center gap-2 rounded-full px-5 py-3 font-bold" onClick={() => setMode('contact')}><MessageCircle size={18}/> Contact owner</button><button className="secondary-button flex items-center justify-center gap-2 rounded-full px-5 py-3 font-bold" onClick={() => setMode('booking')}><CalendarCheck size={18}/> Book a viewing</button><button className="secondary-button flex items-center justify-center gap-2 rounded-full px-5 py-3 font-bold" onClick={toggleSaved}><Heart size={18} fill={saved ? 'currentColor' : 'none'}/> {saved ? 'Saved to favorites' : 'Save to favorites'}</button></div><p className="muted-text mt-5 text-center text-xs">Your request is saved locally in this demo.</p>{mode && <div className="fixed inset-0 z-50 grid place-items-center bg-black/50 p-5"><div className="contact-card w-full max-w-md rounded-3xl p-6"><button className="float-right" onClick={() => { setMode(null); setSent(false); }} aria-label="Close"><X size={18}/></button>{sent ? <div className="success-notice">Your {mode === 'booking' ? 'viewing request' : 'message'} for {propertyTitle} has been sent.</div> : <form onSubmit={(event) => { event.preventDefault(); setSent(true); }}><h2 className="text-2xl font-bold">{mode === 'booking' ? 'Book a viewing' : 'Contact owner'}</h2><p className="muted-text mt-2">{propertyTitle}</p>{mode === 'booking' && <input className="mt-5 w-full" required type="date" min={new Date().toISOString().split('T')[0]}/>}<input className="mt-3 w-full" required type="text" placeholder="Your name"/><input className="mt-3 w-full" required type="email" placeholder="Email address"/>{mode === 'contact' && <textarea className="mt-3 w-full" required rows={4} placeholder="Your message"/>}<button className="gradient-button mt-5 w-full rounded-full px-5 py-3 font-bold" type="submit">Send request</button></form>}</div></div>}</>;
}
