import Link from 'next/link';
import { ArrowRight, BedDouble, CalendarDays, CheckCircle2, FileCheck2, Hammer, LandPlot, MapPin, Plane, Search, ShieldCheck, Sparkles, Trees, Users } from 'lucide-react';
import { properties, propertySection, sectionCatalog } from '../data';
import SiteFooter from './site-footer';
import SiteHeader from './site-header';
import { routes, type AppSection } from '../lib/routes';

type SectionSiteProps = { section: AppSection };
const heroImages: Record<AppSection, string> = {
  trip: 'https://images.unsplash.com/photo-1503220317375-aaad61436b1b?auto=format&fit=crop&w=1800&q=90',
  stay: 'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1800&q=90',
  'buy-home': 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1800&q=90',
  land: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1800&q=90',
};
const copy = {
  trip: { label: 'TRAVEL STUDIO', title: 'Go further.\nFeel more.', text: 'Build a considered trip from destinations, experiences, and stays that belong together.', primary: 'Plan a trip', secondary: 'Browse destinations', nav: 'trip' as const },
  stay: { label: 'STAY COLLECTION', title: 'Arrive well.\nStay longer.', text: 'Find hotels, apartments, villas, and chalets chosen around the way you want to feel.', primary: 'Find a stay', secondary: 'Explore stays', nav: 'stay' as const },
  'buy-home': { label: 'OWNERSHIP STUDIO', title: 'Find a place.\nMake it yours.', text: 'A property search shaped by architecture, location, ownership clarity, and your next chapter.', primary: 'Find a home', secondary: 'Ownership guide', nav: 'buy-home' as const },
  land: { label: 'LAND INTELLIGENCE', title: 'Start with ground.\nBuild with clarity.', text: 'Land opportunities organized around use, access, documents, and long-term potential.', primary: 'Explore land', secondary: 'Decision guide', nav: 'land' as const },
};

function getItems(section: AppSection) { return section === 'land' ? properties.filter((p) => propertySection(p) === 'land') : section === 'buy-home' ? properties.filter((p) => propertySection(p) === 'buy-home') : section === 'stay' || section === 'trip' ? properties.filter((p) => propertySection(p) === 'stay') : []; }

export default function SectionSite({ section }: SectionSiteProps) {
  const content = copy[section]; const catalog = sectionCatalog[section]; const items = getItems(section).slice(0, 6); const isLand = section === 'land'; const isHome = section === 'buy-home'; const isTrip = section === 'trip';
  return <main className={`section-site section-site-${section}`}><SiteHeader section={content.nav}/><section className="section-site-hero" style={{ backgroundImage: `linear-gradient(90deg,rgba(3,17,31,.96),rgba(3,17,31,.76) 36%,rgba(3,17,31,.18)),url(${heroImages[section]})` }}><div><span className="section-kicker">{content.label}</span><h1>{content.title.split('\n').map((line) => <span key={line}>{line}<br/></span>)}</h1><p>{content.text}</p><div className="section-hero-actions"><Link href={routes.search(section)} className="primary-cta"><Search size={16}/>{content.primary}</Link><Link href={isTrip ? '/travel/destinations' : routes.sectionGuide(section)} className="section-text-link">{content.secondary} <ArrowRight size={15}/></Link></div></div><div className="section-hero-stamp"><span>{isLand ? 'LAND / 04' : isHome ? 'OWN / 03' : isTrip ? 'TRAVEL / 01' : 'STAY / 02'}</span><strong>{catalog.featuredAreas[0]}</strong><small>Curated for your next move</small></div></section>
    {isTrip ? <section className="section-planner section-panel" id="search"><div><span className="section-kicker">TRIP BUILDER</span><h2>Start with the feeling.<br/><em>We’ll shape the rest.</em></h2><p>Choose a destination, a pace, and the kind of moments you want to remember.</p></div><div className="planner-options"><Link href="/travel/destinations"><MapPin/><strong>Destination</strong><small>Where do you want to go?</small><ArrowRight/></Link><Link href="/travel/experiences"><Sparkles/><strong>Experience</strong><small>What do you want to feel?</small><ArrowRight/></Link><Link href={routes.search('stay')}><CalendarDays/><strong>Stay</strong><small>Where will you rest?</small><ArrowRight/></Link></div></section> : <section className="section-search-panel section-panel" id="search"><div><span className="section-kicker">{isLand ? 'LAND FINDER' : isHome ? 'HOME FINDER' : 'STAY FINDER'}</span><h2>{isLand ? 'Find ground with a clear purpose.' : isHome ? 'Search for the way you want to live.' : 'Choose a stay that fits your rhythm.'}</h2></div><Link href={routes.search(section)} className="primary-cta">Open full search <ArrowRight size={15}/></Link><div className="section-search-fields"><span><MapPin size={18}/><small>Location</small><strong>{catalog.featuredAreas[0]}</strong></span><span><Search size={18}/><small>{isLand ? 'Use' : isHome ? 'Property type' : 'Stay type'}</small><strong>{isLand ? 'All land' : isHome ? 'All homes' : 'All stays'}</strong></span><span><CheckCircle2 size={18}/><small>Availability</small><strong>{isLand ? 'Verified opportunities' : isHome ? 'Ready to view' : 'Available now'}</strong></span></div></section>}
    <section className="section-content-grid" id="collection"><div className="section-content-intro"><span className="section-kicker">{isLand ? 'CURATED OPPORTUNITIES' : isHome ? 'PROPERTY COLLECTION' : isTrip ? 'PLACES & MOMENTS' : 'THE STAY EDIT'}</span><h2>{isLand ? 'Ground for a bigger plan.' : isHome ? 'The next address starts here.' : isTrip ? 'A better trip has a point of view.' : 'Places that make arrival easy.'}</h2><p>{catalog.promise}</p><Link href={routes.search(section)} className="outline-cta">Explore the collection <ArrowRight size={14}/></Link></div><div className="section-card-grid">{items.map((item, index) => <Link className="section-listing-card" href={routes.property(item.id)} key={item.id}><div className="section-listing-image" style={{ backgroundImage: `linear-gradient(0deg,rgba(3,18,31,.9),rgba(3,18,31,0) 70%),url(${item.image})` }}><span>0{index + 1}</span><small>{item.operation} · {item.type}</small></div><div><strong>{item.title}</strong><p><MapPin size={12}/>{item.location}</p><em>{item.price}</em></div></Link>)}</div></section>
    <section className="section-services section-panel" id="guide"><div><span className="section-kicker">{isLand ? 'MAKE A SOUND DECISION' : isHome ? 'OWNERSHIP, MADE CLEAR' : isTrip ? 'TRAVEL, MADE PERSONAL' : 'EVERY DETAIL CONSIDERED'}</span><h2>{isLand ? 'More than a plot. A direction.' : isHome ? 'More than a listing. A beginning.' : isTrip ? 'More than a booking. A story.' : 'More than a room. A feeling.'}</h2></div><div className="section-service-grid">{catalog.services.map((service, index) => <article key={service}><span>0{index + 1}</span>{isLand ? index === 0 ? <LandPlot/> : index === 1 ? <FileCheck2/> : index === 2 ? <Hammer/> : <Trees/> : isHome ? index === 0 ? <ShieldCheck/> : index === 1 ? <BedDouble/> : index === 2 ? <Users/> : <Sparkles/> : isTrip ? index === 0 ? <Plane/> : index === 1 ? <Sparkles/> : index === 2 ? <CalendarDays/> : <Users/> : index === 0 ? <ShieldCheck/> : index === 1 ? <BedDouble/> : index === 2 ? <MapPin/> : <Sparkles/>}<strong>{service}</strong><p>{isLand ? 'Practical information before the next move.' : isHome ? 'A clearer path to the right decision.' : isTrip ? 'A considered part of your complete journey.' : 'Selected, prepared, and ready for your arrival.'}</p></article>)}</div></section>
    <SiteFooter section={section}/>
  </main>;
}
