export const languages = [
  { code: 'en', nativeName: 'English' },
  { code: 'ar', nativeName: 'العربية' },
  { code: 'zh', nativeName: '中文' },
  { code: 'hi', nativeName: 'हिन्दी' },
  { code: 'es', nativeName: 'Español' },
  { code: 'fr', nativeName: 'Français' },
  { code: 'bn', nativeName: 'বাংলা' },
] as const;

export type Language = (typeof languages)[number]['code'];

export const siteTranslations: Record<Language, { navDestinations:string; navExperiences:string; navDeals:string; navAbout:string; navContact:string; search:string; filters:string; clear:string; results:string; operation:string; propertyType:string; location:string; minPrice:string; maxPrice:string; rooms:string; status:string; all:string; rent:string; sale:string; sort:string; newest:string; footerTagline:string; explore:string; support:string; company:string; newsletter:string; newsletterText:string; subscribe:string; emailPlaceholder:string; privacy:string; terms:string; faq:string }> = {
  en: { navDestinations:'Destinations', navExperiences:'Experiences', navDeals:'Deals', navAbout:'About Us', navContact:'Contact', search:'Search', filters:'Filters', clear:'Clear all', results:'results', operation:'Operation', propertyType:'Property type', location:'City or neighborhood', minPrice:'Min price', maxPrice:'Max price', rooms:'Rooms', status:'Status', all:'All', rent:'For rent', sale:'For sale', sort:'Sort by', newest:'Newest first', footerTagline:'Curated places, meaningful stays, and opportunities worth discovering.', explore:'Explore', support:'Support', company:'Company', newsletter:'Get travel inspiration', newsletterText:'Fresh stays and exclusive deals, delivered to your inbox.', subscribe:'Subscribe', emailPlaceholder:'Your email address', privacy:'Privacy', terms:'Terms', faq:'FAQ' },
  ar: { navDestinations:'الوجهات', navExperiences:'التجارب', navDeals:'العروض', navAbout:'من نحن', navContact:'تواصل معنا', search:'بحث', filters:'الفلاتر', clear:'مسح الكل', results:'نتيجة', operation:'نوع العملية', propertyType:'نوع العقار', location:'المدينة أو الحي', minPrice:'الحد الأدنى للسعر', maxPrice:'الحد الأقصى للسعر', rooms:'الغرف', status:'الحالة', all:'الكل', rent:'للإيجار', sale:'للبيع', sort:'ترتيب حسب', newest:'الأحدث أولًا', footerTagline:'أماكن مختارة، إقامات مميزة، وفرص تستحق الاكتشاف.', explore:'استكشف', support:'الدعم', company:'الشركة', newsletter:'استلهم رحلتك القادمة', newsletterText:'إقامات جديدة وعروض حصرية تصل مباشرة إلى بريدك.', subscribe:'اشترك', emailPlaceholder:'بريدك الإلكتروني', privacy:'الخصوصية', terms:'الشروط', faq:'الأسئلة الشائعة' },
  zh: { navDestinations:'目的地', navExperiences:'体验', navDeals:'优惠', navAbout:'关于我们', navContact:'联系我们', search:'搜索', filters:'筛选', clear:'清除全部', results:'个结果', operation:'交易类型', propertyType:'房产类型', location:'城市或社区', minPrice:'最低价格', maxPrice:'最高价格', rooms:'房间数', status:'房产状态', all:'全部', rent:'出租', sale:'出售', sort:'排序', newest:'最新优先', footerTagline:'精选地点、难忘住宿和值得发现的机会。', explore:'探索', support:'支持', company:'公司', newsletter:'获取旅行灵感', newsletterText:'最新住宿和独家优惠，直接发送到您的邮箱。', subscribe:'订阅', emailPlaceholder:'您的电子邮箱', privacy:'隐私', terms:'条款', faq:'常见问题' },
  hi: { navDestinations:'गंतव्य', navExperiences:'अनुभव', navDeals:'ऑफ़र', navAbout:'हमारे बारे में', navContact:'संपर्क', search:'खोजें', filters:'फ़िल्टर', clear:'सब साफ़ करें', results:'परिणाम', operation:'प्रकार', propertyType:'प्रॉपर्टी प्रकार', location:'शहर या क्षेत्र', minPrice:'न्यूनतम कीमत', maxPrice:'अधिकतम कीमत', rooms:'कमरे', status:'स्थिति', all:'सभी', rent:'किराए के लिए', sale:'बिक्री के लिए', sort:'क्रम', newest:'नवीनतम पहले', footerTagline:'चुने हुए स्थान, यादगार ठहराव और खोजने योग्य अवसर।', explore:'खोजें', support:'सहायता', company:'कंपनी', newsletter:'यात्रा की प्रेरणा पाएं', newsletterText:'नए ठहराव और विशेष ऑफ़र सीधे आपके इनबॉक्स में।', subscribe:'सब्सक्राइब', emailPlaceholder:'आपका ईमेल पता', privacy:'गोपनीयता', terms:'शर्तें', faq:'सामान्य प्रश्न' },
  es: { navDestinations:'Destinos', navExperiences:'Experiencias', navDeals:'Ofertas', navAbout:'Sobre nosotros', navContact:'Contacto', search:'Buscar', filters:'Filtros', clear:'Borrar todo', results:'resultados', operation:'Operación', propertyType:'Tipo de propiedad', location:'Ciudad o zona', minPrice:'Precio mínimo', maxPrice:'Precio máximo', rooms:'Habitaciones', status:'Estado', all:'Todos', rent:'En alquiler', sale:'En venta', sort:'Ordenar', newest:'Más recientes', footerTagline:'Lugares seleccionados, estancias memorables y oportunidades por descubrir.', explore:'Explorar', support:'Soporte', company:'Empresa', newsletter:'Inspírate para viajar', newsletterText:'Nuevas estancias y ofertas exclusivas en tu correo.', subscribe:'Suscribirse', emailPlaceholder:'Tu correo electrónico', privacy:'Privacidad', terms:'Términos', faq:'Preguntas frecuentes' },
  fr: { navDestinations:'Destinations', navExperiences:'Expériences', navDeals:'Offres', navAbout:'À propos', navContact:'Contact', search:'Rechercher', filters:'Filtres', clear:'Tout effacer', results:'résultats', operation:'Opération', propertyType:'Type de bien', location:'Ville ou quartier', minPrice:'Prix minimum', maxPrice:'Prix maximum', rooms:'Chambres', status:'État', all:'Tous', rent:'À louer', sale:'À vendre', sort:'Trier', newest:'Plus récents', footerTagline:'Des lieux choisis, des séjours mémorables et des opportunités à découvrir.', explore:'Explorer', support:'Assistance', company:'Entreprise', newsletter:'Inspirez votre prochain voyage', newsletterText:'Nouveaux séjours et offres exclusives dans votre boîte mail.', subscribe:"S'inscrire", emailPlaceholder:'Votre adresse e-mail', privacy:'Confidentialité', terms:'Conditions', faq:'FAQ' },
  bn: { navDestinations:'গন্তব্য', navExperiences:'অভিজ্ঞতা', navDeals:'অফার', navAbout:'আমাদের সম্পর্কে', navContact:'যোগাযোগ', search:'অনুসন্ধান', filters:'ফিল্টার', clear:'সব মুছুন', results:'ফলাফল', operation:'ধরন', propertyType:'সম্পত্তির ধরন', location:'শহর বা এলাকা', minPrice:'সর্বনিম্ন মূল্য', maxPrice:'সর্বোচ্চ মূল্য', rooms:'রুম', status:'অবস্থা', all:'সব', rent:'ভাড়ার জন্য', sale:'বিক্রয়ের জন্য', sort:'সাজান', newest:'নতুন আগে', footerTagline:'বাছাই করা স্থান, স্মরণীয় থাকা এবং আবিষ্কারের সুযোগ।', explore:'অন্বেষণ', support:'সহায়তা', company:'কোম্পানি', newsletter:'ভ্রমণের অনুপ্রেরণা পান', newsletterText:'নতুন থাকা ও বিশেষ অফার সরাসরি আপনার ইনবক্সে।', subscribe:'সাবস্ক্রাইব', emailPlaceholder:'আপনার ইমেল ঠিকানা', privacy:'গোপনীয়তা', terms:'শর্তাবলি', faq:'প্রায়শই জিজ্ঞাসিত প্রশ্ন' },
};

export const translations: Record<Language, {
  signIn: string; createAccount: string; welcomeBack: string; authSubtitle: string; fullName: string; email: string; phone: string; password: string; confirmPassword: string; remember: string; forgotPassword: string; continue: string; noAccount: string; alreadyAccount: string; chooseRole: string; seeker: string; owner: string; agent: string; acceptTerms: string; passwordStrength: string; weak: string; medium: string; strong: string; backHome: string; language: string; invalidEmail: string; required: string; passwordMismatch: string; accountCreated: string; loginSuccess: string; demoNotice: string;
}> = {
  en: { signIn:'Sign in', createAccount:'Create account', welcomeBack:'Welcome back', authSubtitle:'Manage your property journey from one secure place.', fullName:'Full name', email:'Email address', phone:'Phone number', password:'Password', confirmPassword:'Confirm password', remember:'Remember me', forgotPassword:'Forgot password?', continue:'Continue', noAccount:"Don't have an account?", alreadyAccount:'Already have an account?', chooseRole:'I am joining as', seeker:'Property seeker', owner:'Property owner', agent:'Real estate agent', acceptTerms:'I agree to the Terms of Service and Privacy Policy.', passwordStrength:'Password strength', weak:'Weak', medium:'Medium', strong:'Strong', backHome:'Back to home', language:'Language', invalidEmail:'Enter a valid email address.', required:'This field is required.', passwordMismatch:'Passwords do not match.', accountCreated:'Your account has been created securely.', loginSuccess:'You are now signed in securely.', demoNotice:'Your account is protected with a secure server session.' },
  ar: { signIn:'تسجيل الدخول', createAccount:'إنشاء حساب', welcomeBack:'مرحبًا بعودتك', authSubtitle:'أدر رحلتك العقارية من مكان آمن واحد.', fullName:'الاسم الكامل', email:'البريد الإلكتروني', phone:'رقم الهاتف', password:'كلمة المرور', confirmPassword:'تأكيد كلمة المرور', remember:'تذكرني', forgotPassword:'هل نسيت كلمة المرور؟', continue:'متابعة', noAccount:'ليس لديك حساب؟', alreadyAccount:'لديك حساب بالفعل؟', chooseRole:'سأنضم بصفتي', seeker:'باحث عن عقار', owner:'مالك عقار', agent:'وكيل عقاري', acceptTerms:'أوافق على شروط الخدمة وسياسة الخصوصية.', passwordStrength:'قوة كلمة المرور', weak:'ضعيفة', medium:'متوسطة', strong:'قوية', backHome:'العودة إلى الرئيسية', language:'اللغة', invalidEmail:'أدخل بريدًا إلكترونيًا صالحًا.', required:'هذا الحقل مطلوب.', passwordMismatch:'كلمتا المرور غير متطابقتين.', accountCreated:'تم إنشاء حسابك.', loginSuccess:'تم تسجيل دخولك بنجاح.', demoNotice:'وضع تجريبي: اربط النموذج بخادمك قبل إطلاق الموقع.' },
  zh: { signIn:'登录', createAccount:'创建账户', welcomeBack:'欢迎回来', authSubtitle:'在一个安全的空间管理您的房产之旅。', fullName:'姓名', email:'电子邮箱', phone:'电话号码', password:'密码', confirmPassword:'确认密码', remember:'记住我', forgotPassword:'忘记密码？', continue:'继续', noAccount:'还没有账户？', alreadyAccount:'已经有账户？', chooseRole:'我将以以下身份加入', seeker:'找房者', owner:'房主', agent:'房地产经纪人', acceptTerms:'我同意服务条款和隐私政策。', passwordStrength:'密码强度', weak:'弱', medium:'中等', strong:'强', backHome:'返回首页', language:'语言', invalidEmail:'请输入有效的电子邮箱。', required:'此字段为必填项。', passwordMismatch:'两次密码不一致。', accountCreated:'账户已创建。', loginSuccess:'登录成功。', demoNotice:'演示模式：正式上线前请连接后端。' },
  hi: { signIn:'साइन इन', createAccount:'खाता बनाएं', welcomeBack:'वापसी पर स्वागत है', authSubtitle:'एक सुरक्षित स्थान से अपनी प्रॉपर्टी यात्रा प्रबंधित करें।', fullName:'पूरा नाम', email:'ईमेल पता', phone:'फ़ोन नंबर', password:'पासवर्ड', confirmPassword:'पासवर्ड की पुष्टि करें', remember:'मुझे याद रखें', forgotPassword:'पासवर्ड भूल गए?', continue:'जारी रखें', noAccount:'खाता नहीं है?', alreadyAccount:'पहले से खाता है?', chooseRole:'मैं इस रूप में जुड़ रहा/रही हूं', seeker:'प्रॉपर्टी खोजक', owner:'प्रॉपर्टी मालिक', agent:'रियल एस्टेट एजेंट', acceptTerms:'मैं सेवा की शर्तों और गोपनीयता नीति से सहमत हूं।', passwordStrength:'पासवर्ड की मजबूती', weak:'कमज़ोर', medium:'मध्यम', strong:'मज़बूत', backHome:'होम पर वापस', language:'भाषा', invalidEmail:'मान्य ईमेल पता दर्ज करें।', required:'यह फ़ील्ड आवश्यक है।', passwordMismatch:'पासवर्ड मेल नहीं खाते।', accountCreated:'आपका खाता बना दिया गया है।', loginSuccess:'आप साइन इन हो गए हैं।', demoNotice:'डेमो मोड: प्रोडक्शन से पहले फॉर्म को बैकएंड से जोड़ें।' },
  es: { signIn:'Iniciar sesión', createAccount:'Crear cuenta', welcomeBack:'Bienvenido de nuevo', authSubtitle:'Gestiona tu experiencia inmobiliaria desde un lugar seguro.', fullName:'Nombre completo', email:'Correo electrónico', phone:'Número de teléfono', password:'Contraseña', confirmPassword:'Confirmar contraseña', remember:'Recordarme', forgotPassword:'¿Olvidaste tu contraseña?', continue:'Continuar', noAccount:'¿No tienes una cuenta?', alreadyAccount:'¿Ya tienes una cuenta?', chooseRole:'Me uno como', seeker:'Buscador de propiedades', owner:'Propietario', agent:'Agente inmobiliario', acceptTerms:'Acepto los Términos de servicio y la Política de privacidad.', passwordStrength:'Seguridad de la contraseña', weak:'Débil', medium:'Media', strong:'Fuerte', backHome:'Volver al inicio', language:'Idioma', invalidEmail:'Introduce un correo válido.', required:'Este campo es obligatorio.', passwordMismatch:'Las contraseñas no coinciden.', accountCreated:'Tu cuenta ha sido creada.', loginSuccess:'Has iniciado sesión.', demoNotice:'Modo demo: conecta el formulario a tu backend antes de producción.' },
  fr: { signIn:'Se connecter', createAccount:'Créer un compte', welcomeBack:'Bon retour', authSubtitle:'Gérez votre parcours immobilier depuis un espace sécurisé.', fullName:'Nom complet', email:'Adresse e-mail', phone:'Numéro de téléphone', password:'Mot de passe', confirmPassword:'Confirmer le mot de passe', remember:'Se souvenir de moi', forgotPassword:'Mot de passe oublié ?', continue:'Continuer', noAccount:"Vous n'avez pas de compte ?", alreadyAccount:'Vous avez déjà un compte ?', chooseRole:'Je rejoins en tant que', seeker:'Chercheur immobilier', owner:'Propriétaire', agent:'Agent immobilier', acceptTerms:"J'accepte les conditions d'utilisation et la politique de confidentialité.", passwordStrength:'Force du mot de passe', weak:'Faible', medium:'Moyenne', strong:'Forte', backHome:"Retour à l'accueil", language:'Langue', invalidEmail:'Saisissez une adresse e-mail valide.', required:'Ce champ est obligatoire.', passwordMismatch:'Les mots de passe ne correspondent pas.', accountCreated:'Votre compte a été créé.', loginSuccess:'Vous êtes connecté.', demoNotice:'Mode démo : connectez le formulaire à votre backend avant la mise en production.' },
  bn: { signIn:'সাইন ইন', createAccount:'অ্যাকাউন্ট তৈরি করুন', welcomeBack:'আবার স্বাগতম', authSubtitle:'একটি নিরাপদ জায়গা থেকে আপনার সম্পত্তির যাত্রা পরিচালনা করুন।', fullName:'পুরো নাম', email:'ইমেল ঠিকানা', phone:'ফোন নম্বর', password:'পাসওয়ার্ড', confirmPassword:'পাসওয়ার্ড নিশ্চিত করুন', remember:'আমাকে মনে রাখুন', forgotPassword:'পাসওয়ার্ড ভুলে গেছেন?', continue:'চালিয়ে যান', noAccount:'অ্যাকাউন্ট নেই?', alreadyAccount:'ইতিমধ্যে অ্যাকাউন্ট আছে?', chooseRole:'আমি যোগ দিচ্ছি', seeker:'সম্পত্তি অনুসন্ধানকারী', owner:'সম্পত্তির মালিক', agent:'রিয়েল এস্টেট এজেন্ট', acceptTerms:'আমি পরিষেবার শর্তাবলি ও গোপনীয়তা নীতিতে সম্মত।', passwordStrength:'পাসওয়ার্ডের শক্তি', weak:'দুর্বল', medium:'মাঝারি', strong:'শক্তিশালী', backHome:'হোমে ফিরে যান', language:'ভাষা', invalidEmail:'একটি বৈধ ইমেল ঠিকানা লিখুন।', required:'এই ক্ষেত্রটি আবশ্যক।', passwordMismatch:'পাসওয়ার্ড মিলছে না।', accountCreated:'আপনার অ্যাকাউন্ট তৈরি হয়েছে।', loginSuccess:'আপনি সাইন ইন করেছেন।', demoNotice:'ডেমো মোড: প্রোডাকশনের আগে ফর্মটি ব্যাকএন্ডের সাথে যুক্ত করুন।' },
};
