'use client';

import Link from 'next/link';
import { FormEvent, useEffect, useState } from 'react';
import { ArrowRight, Building2, CalendarCheck, ChevronLeft, ChevronRight, CreditCard, Headphones, House, Landmark, MapPin, Plane, Search, ShieldCheck, Sparkles, Sunrise, Trees, Utensils, Users, X } from 'lucide-react';
import { useSiteTheme } from './components/theme-provider';
import SiteFooter from './components/site-footer';
import SiteHeader from './components/site-header';
import DateRangePicker from './components/date-range-picker';
import TravelerPicker from './components/traveler-picker';
import WelcomeScreen from './components/welcome-screen';
import { routes, type AppSection } from './lib/routes';

type Intent = AppSection;
type Destination = { name: string; price: string; image: string };
type ModeCard = [string, string, React.ReactNode];
type HomeMode = {
  slides: { image: string; kicker: string; title: [string, string, string]; text: string }[];
  destinations: Destination[];
  eyebrow: string; title: string; emphasis: string; description: string;
  storyLabel: string; storyTitle: string; storyEmphasis: string; storyImage: string; storyButton: string;
  searchLabel: string; searchPlaceholder: string; searchTypeLabel: string; searchTypeOptions: string[];
  cards: ModeCard[]; benefits: [string, string, React.ReactNode][]; newsletterTitle: string; newsletterText: string;
};

const image = (id: string, width = 900) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${width}&q=90`;
const travelDestinations: Destination[] = [
  { name: 'Cairo, Egypt', price: 'From EGP 299', image: image('photo-1568322445389-f64ac2515020') },
  { name: 'Luxor, Egypt', price: 'From EGP 349', image: image('photo-1539650116574-75c0c6d73f6e') },
  { name: 'Sharm El Sheikh', price: 'From EGP 429', image: image('photo-1548013146-72479768bada') },
  { name: 'Siwa Oasis, Egypt', price: 'From EGP 319', image: image('photo-1500534623283-312aade485b7') },
  { name: 'Bali, Indonesia', price: 'From EGP 499', image: image('photo-1537996194471-e657df975ab4') },
  { name: 'Santorini, Greece', price: 'From EGP 699', image: image('photo-1570077188670-e3a8d69ac5ff') },
  { name: 'Maldives', price: 'From EGP 799', image: image('photo-1514282401047-d79a71a590e8') },
  { name: 'Swiss Alps', price: 'From EGP 899', image: image('photo-1501785888041-af3ef285b470') },
];
const stayDestinations: Destination[] = [
  { name: 'North Coast, Egypt', price: 'From EGP 3,850 / night', image: image('photo-1600607687920-4e2a09cf159d') },
  { name: 'Dahab, South Sinai', price: 'From EGP 1,850 / night', image: image('photo-1600566753190-17f0baa2a6c3') },
  { name: 'El Gouna, Egypt', price: 'From EGP 5,900 / night', image: image('photo-1600607688969-a5bfcd646154') },
  { name: 'Marsa Alam, Egypt', price: 'From EGP 4,750 / night', image: image('photo-1602002418082-a4443e081dd1') },
];
const homeDestinations: Destination[] = [
  { name: 'New Cairo Villa', price: 'EGP 8.5M', image: image('photo-1600607687939-ce8a6c25118c') },
  { name: 'North Coast Home', price: 'EGP 6.9M', image: image('photo-1600585154340-be6161a56a0c') },
  { name: 'Sharm Villa', price: 'EGP 4.85M', image: image('photo-1613490493576-7fde63acd811') },
  { name: 'New Cairo Loft', price: 'EGP 3.15M', image: image('photo-1600566753190-17f0baa2a6c3') },
];
const landDestinations: Destination[] = [
  { name: 'Dahab Eco Plot', price: 'EGP 1.65M · Residential', image: image('photo-1500534623283-312aade485b7') },
  { name: 'Ras Sudr Plot', price: 'EGP 1.2M · Hospitality', image: image('photo-1500382017468-9049fed747ef') },
  { name: 'Fayoum Farm Land', price: 'EGP 1.05M · Agricultural', image: image('photo-1464226184884-fa280b87c399') },
  { name: 'Ain Sokhna Land', price: 'EGP 750K · Commercial', image: image('photo-1511739001486-6bfe10ce785f') },
];
const landSteps = [
  ['01', 'Confirm the ground', 'Review ownership, boundaries, access roads, utilities, and the documents attached to the opportunity.', <ShieldCheck size={20}/>],
  ['02', 'Test the potential', 'Match the plot with its realistic use: home, farm, hospitality, or a commercial development.', <MapPin size={20}/>],
  ['03', 'Plan the next move', 'Move from a promising location to a clear decision with practical guidance and a defined next step.', <Landmark size={20}/>],
] as [string, string, string, React.ReactNode][];
const cards = {
  trip: [['Adventure', 'Thrilling activities in stunning locations.', <Plane size={19}/>], ['Cultural tours', 'Meet the people, rituals, and stories behind every place.', <Landmark size={19}/>], ['Relaxation', 'Trade the rush for still water and slow afternoons.', <Sunrise size={19}/>], ['Food & drink', 'Taste the destination through its markets and tables.', <Utensils size={19}/>]],
  stay: [['Comfort', 'Thoughtful spaces with everything you need to settle in.', <House size={19}/>], ['Character', 'Places with a story, a point of view, and a sense of place.', <Sparkles size={19}/>], ['Location', 'Stay close to the sea, city, nature, or the people you came to see.', <MapPin size={19}/>], ['Service', 'Clear support before, during, and after your stay.', <Headphones size={19}/>]],
  'buy-home': [['Design', 'Homes and chalets chosen for how they feel to live in.', <Building2 size={19}/>], ['Community', 'Considered locations close to the life you want to build.', <Users size={19}/>], ['Value', 'Properties selected for location, quality, and lasting potential.', <CreditCard size={19}/>], ['Ownership', 'Guidance from first viewing to a confident next step.', <ShieldCheck size={19}/>]],
  land: [['Location', 'Access, surroundings, and the facts behind every opportunity.', <MapPin size={19}/>], ['Potential', 'Residential, agricultural, commercial, and hospitality possibilities.', <Trees size={19}/>], ['Planning', 'Clear information about use, access, and development direction.', <Landmark size={19}/>], ['Growth', 'Land selected for a practical long-term investment case.', <Sparkles size={19}/>]],
} as Record<Intent, ModeCard[]>;
const baseSlide = (mode: Intent, title: [string, string, string], text: string, photo: string, kicker: string) => ({ image: photo, kicker, title, text });
const homeModes: Record<Intent, HomeMode> = {
  trip: { slides: [baseSlide('trip', ['Explore.', 'Dream.', 'Discover.'], 'Build a complete journey around places, experiences, and memories worth keeping.', image('photo-1503220317375-aaad61436b1b', 1800), 'YOUR NEXT ESCAPE'), baseSlide('trip', ['Move.', 'Wander.', 'Feel more.'], 'From island mornings to mountain air, your next story starts here.', image('photo-1537996194471-e657df975ab4b', 1800), 'GO SOMEWHERE BEAUTIFUL')], destinations: travelDestinations, eyebrow: 'TOP DESTINATIONS', title: 'Popular', emphasis: 'destinations', description: 'Discover destinations, stays, and experiences curated around the way you want to travel.', storyLabel: 'FEATURED JOURNEY', storyTitle: 'Live Your', storyEmphasis: 'Best Story.', storyImage: image('photo-1507525428034-b723cf961d3e', 1200), storyButton: 'Discover journey', searchLabel: 'Where are you going?', searchPlaceholder: 'Choose a destination', searchTypeLabel: 'Trip style', searchTypeOptions: ['All trips', 'Beach escape', 'Cultural tour', 'Adventure'], cards: cards.trip, benefits: [['Verified partners', 'Curated places and experiences.', <ShieldCheck size={20}/>], ['Human support', 'Help whenever your plans change.', <Headphones size={20}/>], ['Flexible planning', 'Build a trip around your priorities.', <CalendarCheck size={20}/>], ['Secure requests', 'Your booking details stay protected.', <CreditCard size={20}/>]], newsletterTitle: 'Make room for your next escape', newsletterText: 'Get travel inspiration and new opportunities before everyone else.' },
  stay: { slides: [baseSlide('stay', ['Stay.', 'Breathe.', 'Reconnect.'], 'Find hotels, apartments, villas, and chalets where every detail feels considered.', image('photo-1600607687920-4e2a09cf159d', 1800), 'STAYS MADE FOR YOU'), baseSlide('stay', ['Arrive.', 'Unwind.', 'Feel at home.'], 'Verified stays with the space, comfort, and character your trip deserves.', image('photo-1600566753190-17f0baa2a6c3', 1800), 'YOUR HOME AWAY')], destinations: stayDestinations, eyebrow: 'CURATED STAYS', title: 'Places worth', emphasis: 'staying in.', description: 'Comfortable stays, thoughtful spaces, and homes selected for the feeling they leave behind.', storyLabel: 'FEATURED STAY', storyTitle: 'Your next', storyEmphasis: 'favorite place.', storyImage: image('photo-1499793983690-e29da59ef1c', 1200), storyButton: 'View this stay', searchLabel: 'Destination', searchPlaceholder: 'Where to?', searchTypeLabel: 'Stay type', searchTypeOptions: ['All stays', 'Apartments', 'Villas', 'Chalets'], cards: cards.stay, benefits: [['Verified stays', 'Places reviewed for a better arrival.', <ShieldCheck size={20}/>], ['24/7 support', 'We are here before and during your stay.', <Headphones size={20}/>], ['Easy booking', 'Clear dates, guests, and requests.', <CalendarCheck size={20}/>], ['Secure requests', 'Your booking details stay protected.', <CreditCard size={20}/>]], newsletterTitle: 'Stay longer. Feel more.', newsletterText: 'Receive handpicked stays and private offers in your inbox.' },
  'buy-home': { slides: [baseSlide('buy-home', ['Own.', 'Belong.', 'Begin.'], 'Find homes and chalets selected for the life you are ready to build.', image('photo-1600607687939-ce8a6c25118c', 1800), 'A PLACE TO CALL YOURS'), baseSlide('buy-home', ['Live.', 'Invest.', 'Grow.'], 'Beautiful properties with the space, location, and potential to move forward.', image('photo-1600566753086-00f18fb6b3ea', 1800), 'FIND YOUR NEXT CHAPTER')], destinations: homeDestinations, eyebrow: 'PROPERTY COLLECTION', title: 'Find your', emphasis: 'next address.', description: 'Homes and chalets chosen for their design, location, and lasting value.', storyLabel: 'FEATURED PROPERTY', storyTitle: 'Make it', storyEmphasis: 'yours.', storyImage: image('photo-1600607687939-ce8a6c25118c', 1200), storyButton: 'View property', searchLabel: 'Preferred location', searchPlaceholder: 'City or community', searchTypeLabel: 'Property type', searchTypeOptions: ['All homes', 'Apartments', 'Villas', 'Chalets'], cards: cards['buy-home'], benefits: [['Verified properties', 'Clear details before you book a viewing.', <ShieldCheck size={20}/>], ['Legal guidance', 'A clearer path from viewing to ownership.', <Landmark size={20}/>], ['Location insight', 'Understand the community and surrounding services.', <MapPin size={20}/>], ['Viewing support', 'Arrange the next step with our team.', <Headphones size={20}/>]], newsletterTitle: 'Find a place to call yours', newsletterText: 'Receive new homes, chalets, and private property listings.' },
  land: { slides: [baseSlide('land', ['Plan.', 'Build.', 'Grow.'], 'Explore land with the location and potential to turn your vision into something real.', image('photo-1500382017468-9049fed747ef', 1800), 'SPACE FOR WHAT IS NEXT'), baseSlide('land', ['More.', 'Than a plot.', 'A direction.'], 'Residential, agricultural, and commercial opportunities selected with care.', image('photo-1464226184884-fa280b87c399', 1800), 'INVEST IN POSSIBILITY')], destinations: landDestinations, eyebrow: 'LAND OPPORTUNITIES', title: 'Ground for', emphasis: 'your vision.', description: 'Land opportunities for living, farming, development, and investment—with clarity at every step.', storyLabel: 'FEATURED OPPORTUNITY', storyTitle: 'Start from', storyEmphasis: 'the ground up.', storyImage: image('photo-1500382017468-9049fed747ef', 1200), storyButton: 'View land opportunity', searchLabel: 'Land location', searchPlaceholder: 'City or land area', searchTypeLabel: 'Land use', searchTypeOptions: ['All land', 'Residential land', 'Agricultural land', 'Commercial land'], cards: cards.land, benefits: [['Verified ownership', 'Start with clear property information.', <ShieldCheck size={20}/>], ['Legal documentation', 'Understand the documents before a decision.', <Landmark size={20}/>], ['Location analysis', 'See access, surroundings, and potential use.', <MapPin size={20}/>], ['Investment guidance', 'Move forward with practical support.', <Headphones size={20}/>]], newsletterTitle: 'Get verified land opportunities', newsletterText: 'Receive new plots, development opportunities, and investment updates.' },
};
const intents = [{ id: 'trip' as Intent, label: 'Book a trip', description: 'Plan flights, experiences, and unforgettable escapes.', icon: <Plane size={22}/>, accent: 'intent-sky' }, { id: 'stay' as Intent, label: 'Book a hotel or home', description: 'Find verified hotels, apartments, villas, and chalets.', icon: <House size={22}/>, accent: 'intent-teal' }, { id: 'buy-home' as Intent, label: 'Buy a home or chalet', description: 'Discover homes and holiday properties made for your next chapter.', icon: <Building2 size={22}/>, accent: 'intent-gold' }, { id: 'land' as Intent, label: 'Buy or rent land', description: 'Explore land opportunities for living, farming, or investment.', icon: <Trees size={22}/>, accent: 'intent-green' }];
const todayIso = () => { const date = new Date(); return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`; };

export default function Home() {
  const { darkMode } = useSiteTheme();
  const [intent, setIntent] = useState<Intent>('stay'); const [heroIndex, setHeroIndex] = useState(0); const [destination, setDestination] = useState(''); const [checkIn, setCheckIn] = useState(''); const [checkOut, setCheckOut] = useState(''); const [travelers, setTravelers] = useState('2'); const [propertyType, setPropertyType] = useState('all'); const [landOperation, setLandOperation] = useState('sale'); const [destinationSlide, setDestinationSlide] = useState(0); const [showVideo, setShowVideo] = useState(false); const [showWelcome, setShowWelcome] = useState(true);
  const mode = homeModes[intent]; const hero = mode.slides[heroIndex]; const pages = Math.ceil(mode.destinations.length / 4);
  useEffect(() => { const requested = new URLSearchParams(window.location.search).get('mode') as Intent | null; if (requested && ['trip', 'stay', 'buy-home', 'land'].includes(requested)) { setIntent(requested); setShowWelcome(false); } }, []);
  useEffect(() => { setHeroIndex(0); setDestinationSlide(0); setDestination(''); setPropertyType('all'); setLandOperation('sale'); setCheckIn(''); setCheckOut(''); setTravelers('2'); }, [intent]);
  useEffect(() => { const timer = window.setInterval(() => setHeroIndex((current) => (current + 1) % mode.slides.length), 6500); return () => window.clearInterval(timer); }, [intent, mode.slides.length]);
  useEffect(() => { const timer = window.setInterval(() => setDestinationSlide((current) => (current + 1) % pages), 5600); return () => window.clearInterval(timer); }, [pages, intent]);
  const submitSearch = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const params = new URLSearchParams({ mode: intent }); if (destination) params.set('location', destination); if (propertyType !== 'all') params.set('type', propertyType); if (intent === 'land') params.set('operation', landOperation); if (intent === 'trip' || intent === 'stay') { if (checkIn) params.set('checkIn', checkIn); if (checkOut) params.set('checkOut', checkOut); if (travelers) params.set('travelers', travelers); } window.location.href = `${routes.search(intent)}${params.toString().replace(`mode=${intent}`, '')}`; };
  const chooseDestination = (name: string) => { setDestination(name); document.querySelector('.travel-search')?.scrollIntoView({ behavior: 'smooth', block: 'center' }); window.setTimeout(() => document.querySelector<HTMLInputElement>('input[aria-label="Destination"]')?.focus(), 450); };
  return <main className={`travel-home intent-theme-${intent} ${darkMode ? 'dark-theme' : 'light-theme'}`}>
    {showWelcome && <WelcomeScreen onChoose={(nextIntent) => { setIntent(nextIntent); setShowWelcome(false); }}/>}<section className="travel-frame"><SiteHeader section={intent}/>
      <section className={`travel-hero mode-hero-${intent}`} style={{ backgroundImage: `linear-gradient(90deg,rgba(3,17,31,.95) 0%,rgba(3,17,31,.8) 30%,rgba(3,17,31,.18) 75%),url('${hero.image}')` }}><div className="hero-copy" key={`${intent}-${heroIndex}`} aria-live="polite"><div className="hero-kicker"><Sparkles size={14}/> {hero.kicker}</div><h1>{hero.title[0]}<br/>{hero.title[1]}<br/><em>{hero.title[2]}</em></h1><p>{hero.text}</p><div className="hero-ctas"><Link href={routes.section(intent)} className="primary-cta"><Search size={15}/> {intent === 'land' ? 'Explore land' : intent === 'buy-home' ? 'Explore properties' : intent === 'stay' ? 'Find a stay' : 'Explore trips'}</Link><button className="video-cta" type="button" onClick={() => setShowVideo(true)}><span>▶</span> Watch Video</button></div></div><div className="hero-progress" aria-label={`Slide ${heroIndex + 1} of ${mode.slides.length}`}>{mode.slides.map((slide, index) => <button key={slide.kicker} type="button" aria-label={`Show slide ${index + 1}`} className={index === heroIndex ? 'active' : ''} onClick={() => setHeroIndex(index)}/>)}</div></section>
      {showVideo && <div className="luxury-video-overlay" role="dialog" aria-modal="true" aria-label="Al-Aroum travel film" onClick={() => setShowVideo(false)}><div className="luxury-video-modal" onClick={(event) => event.stopPropagation()}><button type="button" className="luxury-video-close" aria-label="Close video" onClick={() => setShowVideo(false)}><X size={20}/></button><div className="luxury-video-heading"><span>AL-AROUM JOURNAL</span><h2>A clearer way<br/><em>to make your next move.</em></h2></div><video autoPlay controls playsInline poster={hero.image}><source src="https://cdn.coverr.co/videos/coverr-aerial-view-of-a-beach-1574/1080p.mp4" type="video/mp4"/>Your browser does not support video playback.</video></div></div>}
      <form className={`travel-search intent-${intent}`} onSubmit={submitSearch}><label className="search-item"><MapPin size={21}/><span><small>{mode.searchLabel}</small><input name="location" aria-label="Destination" value={destination} onChange={(event) => setDestination(event.target.value)} placeholder={mode.searchPlaceholder}/></span></label>{(intent === 'trip' || intent === 'stay') && <><DateRangePicker checkIn={checkIn} checkOut={checkOut} minDate={todayIso()} onCheckInChange={setCheckIn} onCheckOutChange={setCheckOut}/><TravelerPicker value={travelers} onChange={setTravelers}/></>}{(intent === 'buy-home' || intent === 'land') && <><label className="search-item mode-select-item"><Landmark size={21}/><span><small>{mode.searchTypeLabel}</small><select value={propertyType} onChange={(event) => setPropertyType(event.target.value)} aria-label={mode.searchTypeLabel}>{mode.searchTypeOptions.map((option) => <option key={option} value={option.toLowerCase().includes('all') ? 'all' : option}>{option}</option>)}</select></span></label>{intent === 'land' && <label className="search-item mode-select-item"><Building2 size={21}/><span><small>Purpose</small><select value={landOperation} onChange={(event) => setLandOperation(event.target.value)} aria-label="Land purpose"><option value="sale">Buy land</option><option value="rent">Rent land</option></select></span></label>}</>}<button className="search-submit" type="submit" aria-label="Search"><Search size={19}/></button></form>
      {intent === 'land' ? <section id="destinations" className="land-opportunities-section"><div className="land-section-intro"><span className="eyebrow">LAND OPPORTUNITIES</span><h2>Choose a plot<br/><em>with a reason.</em></h2><p>Every opportunity is grouped by the decision it supports, not by a generic destination list.</p><Link href="/search?mode=land" className="outline-cta">Browse all land <ArrowRight size={14}/></Link></div><div className="land-opportunity-grid">{landDestinations.map((item, index) => <article className="land-opportunity-card" key={item.name} style={{ backgroundImage: `linear-gradient(0deg,rgba(3,18,31,.94),rgba(3,18,31,.08) 78%),url(${item.image})` }}><span className="land-card-index">0{index + 1}</span><div><small>{index === 0 ? 'Build a retreat' : index === 1 ? 'Hospitality potential' : index === 2 ? 'Grow and produce' : 'Develop with access'}</small><strong>{item.name}</strong><span>{item.price}</span><Link href={`/search?mode=land&location=${encodeURIComponent(item.name)}`}>Review opportunity <ArrowRight size={14}/></Link></div></article>)}</div></section> : <section id="destinations" className="travel-section destinations-section"><div className="section-heading"><div><span className="eyebrow">{mode.eyebrow}</span><h2>{mode.title} <em>{mode.emphasis}</em></h2></div><div className="carousel-actions"><button type="button" aria-label="Previous destinations" onClick={() => setDestinationSlide((current) => (current - 1 + pages) % pages)}><ChevronLeft size={16}/></button><button type="button" aria-label="Next destinations" onClick={() => setDestinationSlide((current) => (current + 1) % pages)}><ChevronRight size={16}/></button><Link href={`/search?mode=${intent}`} className="section-link">View all <ArrowRight size={14}/></Link></div></div><div className="destination-carousel"><div className="destination-track" style={{ transform: `translateX(-${destinationSlide * 100}%)` }}>{Array.from({ length: pages }, (_, page) => <div className="destination-slide" key={page}>{mode.destinations.slice(page * 4, page * 4 + 4).map((item) => <article className="destination-card" key={item.name} style={{ backgroundImage: `linear-gradient(0deg,rgba(3,18,31,.86),rgba(3,18,31,0) 70%),url(${item.image})` }} onClick={() => chooseDestination(item.name)} role="link" tabIndex={0}><div><strong>{item.name}</strong><small>{item.price}</small></div><button type="button" aria-label={`Explore ${item.name}`} onClick={(event) => { event.stopPropagation(); chooseDestination(item.name); }}><ArrowRight size={16}/></button></article>)}</div>)}</div></div><div className="carousel-dots">{Array.from({ length: pages }, (_, index) => <button type="button" key={index} aria-label={`Show destination slide ${index + 1}`} className={index === destinationSlide ? 'active' : ''} onClick={() => setDestinationSlide(index)}/>)}</div></section>}
      {intent === 'land' ? <section id="experiences" className="land-diligence-section"><div className="land-section-intro"><span className="eyebrow">HOW WE HELP YOU DECIDE</span><h2>From open land<br/><em>to a clear plan.</em></h2><p>Land deserves more than a beautiful photo. We organize the practical questions before you commit.</p><a href="#deals" className="outline-cta">Speak with an advisor <ArrowRight size={14}/></a></div><div className="land-diligence-content"><div className="land-step-grid">{landSteps.map(([number, title, description, icon]) => <article key={number}><span className="land-step-icon">{icon}</span><small>{number}</small><strong>{title}</strong><p>{description}</p></article>)}</div><article className="land-advisor-card"><div><span className="eyebrow">LAND ADVISORY</span><h3>Know the plot<br/><em>before you build.</em></h3><p>Ask for a focused review of access, use, documents, and next actions for any listed opportunity.</p><Link href="/contact" className="story-action">Request a review <ArrowRight size={14}/></Link></div></article></div></section> : <section id="experiences" className="travel-section experiences-section"><div className="experience-intro"><span className="eyebrow">{intent === 'trip' ? 'TRAVEL EXPERIENCES' : intent === 'stay' ? 'THE STAY EDIT' : 'OWNERSHIP GUIDE'}</span><h2>{mode.title}<br/><em>{mode.emphasis}</em></h2><p>{mode.description}</p><a href="#deals" className="outline-cta">See how it works <ArrowRight size={14}/></a></div><div className="experience-content"><div className="experience-types">{mode.cards.map(([title, description, icon]) => <article key={title}><span className="experience-icon">{icon}</span><strong>{title}</strong><p>{description}</p></article>)}</div><article className="story-card" style={{ backgroundImage: `linear-gradient(90deg,rgba(4,20,34,.88),rgba(4,20,34,.18)),url(${mode.storyImage})` }}><div><span>{mode.storyLabel}</span><h3>{mode.storyTitle}<br/><em>{mode.storyEmphasis}</em></h3><Link href={`/search?mode=${intent}`} className="story-action">{mode.storyButton} <ArrowRight size={14}/></Link></div><button type="button" className="play-button" aria-label={`Play ${mode.storyLabel.toLowerCase()}`} onClick={() => setShowVideo(true)}>▶</button></article></div></section>}
      <section id="deals" className={`deals-section ${intent === 'land' ? 'land-deals-section' : ''}`}><div className="deal-copy"><span className="eyebrow">{intent === 'land' ? 'LAND ADVISORY DESK' : intent === 'buy-home' ? 'PROPERTY UPDATES' : intent === 'stay' ? 'STAY IN THE LOOP' : 'TRAVEL UPDATES'}</span><h2>{intent === 'land' ? 'Make the next land decision with confidence.' : mode.newsletterTitle}</h2><p>{intent === 'land' ? 'Share the area and the kind of opportunity you want. Our team will point you to a relevant next step.' : mode.newsletterText}</p></div><div className="deal-form"><input aria-label="Email address" type="email" placeholder={intent === 'land' ? 'Your email for a land review' : 'Enter your email'}/><button type="submit">{intent === 'land' ? 'Request review' : 'Subscribe'}</button></div></section>
      <section className="benefits-strip">{mode.benefits.map(([title, text, icon]) => <Benefit key={title} icon={icon} title={title} text={text}/>)}</section><SiteFooter/>
    </section>
  </main>;
}
function Benefit({ icon, title, text }: { icon: React.ReactNode; title: string; text: string }) { return <div className="benefit"><span>{icon}</span><div><strong>{title}</strong><small>{text}</small></div></div>; }
