import Link from 'next/link';
import { ArrowRight, Check, Clock3, Percent, Sparkles, Tag } from 'lucide-react';
import SiteHeader from '../components/site-header';
import SiteFooter from '../components/site-footer';
import { routes } from '../lib/routes';
const offers = [
  ['FIRST ESCAPE','30% off your first trip','A little encouragement to go somewhere new.','https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1000&q=90','blue'],
  ['LONGER STAYS','Stay seven, save more','Make more time for the places you love.','https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?auto=format&fit=crop&w=1000&q=90','teal'],
  ['LAST MINUTE','Beautiful places, closer','Spontaneous plans deserve beautiful settings.','https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=1000&q=90','gold'],
];
export default function DealsPage() { return <main className="deals-page"><SiteHeader section="stay"/><section className="deals-hero"><div><span className="eyebrow">TRAVEL SMARTER</span><h1>More reasons<br/><em>to go.</em></h1><p>Thoughtful offers for the trips you have been imagining.</p><Link href={routes.search('stay')} className="primary-cta">Explore available stays <ArrowRight size={15}/></Link></div><div className="deal-stamp"><Percent size={26}/><strong>UP TO<br/><b>30%</b><br/>OFF</strong></div></section><section className="offer-section"><div className="offer-heading"><div><span className="eyebrow">HANDPICKED FOR YOU</span><h2>Good trips.<br/><em>Better value.</em></h2></div><p>Offers change with the season, but the feeling of finding a great place stays the same.</p></div><div className="offer-grid">{offers.map(([label,title,text,image,accent]) => <article className={`offer-card ${accent}`} key={title}><div className="offer-image" style={{backgroundImage:`linear-gradient(0deg,rgba(3,18,31,.8),rgba(3,18,31,.05) 75%),url(${image})`}}><span>{label}</span><Tag size={17}/></div><div className="offer-body"><h3>{title}</h3><p>{text}</p><Link href={routes.search('stay')}>See stays <ArrowRight size={14}/></Link></div></article>)}</div></section><section className="deal-perks"><div><Sparkles size={22}/><strong>Members get more</strong><p>Join Al-Aroum for early access to new offers and private rates.</p></div><div><Clock3 size={22}/><strong>Offers with a pulse</strong><p>We keep the deals fresh, seasonal, and worth opening.</p></div><div><Check size={22}/><strong>Clear from the start</strong><p>No confusing conditions. Just useful, honest value.</p></div></section><section className="deal-signup"><div><span className="eyebrow">DON'T MISS THE GOOD ONES</span><h2>Get the next deal<br/>in your inbox.</h2></div><form><input type="email" placeholder="Your email address"/><button>Subscribe <ArrowRight size={15}/></button></form></section><SiteFooter/></main>; }
