CREATE DATABASE IF NOT EXISTS al_aroum CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE al_aroum;
CREATE TABLE IF NOT EXISTS Property (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  city VARCHAR(120) NOT NULL,
  type ENUM('APARTMENT','VILLA','CHALET','LAND') NOT NULL,
  purpose ENUM('RENT','SALE') NOT NULL,
  price DECIMAL(12,2) NOT NULL,
  imageUrl VARCHAR(500),
  beds INT DEFAULT 0,
  guests INT DEFAULT 0,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP
);
