import Link from 'next/link';
import { ArrowRight, Camera, Coffee, Mountain, Waves } from 'lucide-react';
import SiteHeader from '../components/site-header';
import SiteFooter from '../components/site-footer';
const items = [
  ['Adventure','Follow the trail, climb higher, and let the landscape surprise you.',<Mountain size={21}/>,'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1000&q=90'],
  ['Cultural Tours','Meet the people, rituals, and stories that give a place its soul.',<Camera size={21}/>,'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=1000&q=90'],
  ['Relaxation','Trade the rush for still water, warm light, and slow afternoons.',<Waves size={21}/>,'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1000&q=90'],
  ['Food & Drink','Taste the destination through its markets, tables, and traditions.',<Coffee size={21}/>,'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=1000&q=90'],
];
export default function ExperiencesPage() { return <main className="experiences-page"><SiteHeader/><section className="experience-hero"><div><span className="eyebrow">BEYOND THE STAY</span><h1>Make room for<br/><em>the unexpected.</em></h1><p>The best trips are not measured in places visited, but in the moments you bring home.</p><Link href="/search" className="experience-play"><span>▶</span> Find your experience</Link></div><div className="experience-orbit"><span>01</span><i/><span>04</span></div></section><section className="experience-list"><div className="experience-list-heading"><span className="eyebrow">CHOOSE YOUR OWN STORY</span><h2>What are you<br/><em>in the mood for?</em></h2></div><div className="experience-rows">{items.map(([title,text,icon,image], index) => <Link href="/search" className="experience-row" key={String(title)}><span className="experience-number">0{index+1}</span><span className="experience-row-icon">{icon}</span><span className="experience-row-copy"><strong>{title}</strong><small>{text}</small></span><img src={String(image)} alt={String(title)}/><ArrowRight className="experience-arrow" size={18}/></Link>)}</div></section><section className="experience-quote"><span>“</span><blockquote>We travel not to escape life,<br/>but for life not to escape us.</blockquote><small>— A slower way to discover the world</small></section><SiteFooter/></main>; }
