 'use client';

import Link from 'next/link';
import { BarChart3, Bell, Heart, LayoutDashboard, MessageCircle, Moon, Plus, Settings, Sun, Users } from 'lucide-react';
import { properties } from '../data';
import { useSiteTheme } from '../components/theme-provider';
import { useEffect, useState } from 'react';

export default function DashboardPage() {
  const { darkMode, toggleTheme } = useSiteTheme();
  const [user, setUser] = useState<{ name: string; role: string } | null>(null);
  const [checking, setChecking] = useState(true);
  useEffect(() => { const controller = new AbortController(); const timeout = window.setTimeout(() => controller.abort(), 5000); fetch('/api/auth/me', { signal: controller.signal }).then((response) => response.ok ? response.json() : null).then((result) => setUser(result?.user || null)).catch(() => setUser(null)).finally(() => { window.clearTimeout(timeout); setChecking(false); }); return () => { window.clearTimeout(timeout); controller.abort(); }; }, []);
  if (checking) return <main className="app-shell min-h-screen grid place-items-center"><p className="muted-text">Loading your dashboard...</p></main>;
  if (!user) return <main className="app-shell min-h-screen grid place-items-center p-6"><div className="contact-card max-w-md rounded-3xl p-8 text-center"><h1 className="display-title text-3xl font-bold">Sign in required</h1><p className="muted-text mt-3">Sign in to manage your saved properties, requests, and account.</p><Link href="/login" className="gradient-button mt-6 rounded-full px-5 py-3 font-bold">Sign in</Link></div></main>;
  return <main className="app-shell min-h-screen px-5 py-8 md:px-10"><div className="mx-auto max-w-7xl"><header className="mb-8 flex items-center justify-between"><div><p className="teal-text text-sm font-bold">لوحة التحكم</p><h1 className="display-title mt-1 text-4xl font-bold">مساحتك العقارية</h1></div><div className="flex gap-3"><button aria-label="Toggle theme" className="icon-button" onClick={toggleTheme}>{darkMode ? <Sun size={18}/> : <Moon size={18}/>}</button><button aria-label="Notifications" className="icon-button"><Bell size={18}/></button><Link href="/" className="secondary-button rounded-full px-4 py-2 text-sm">الموقع الرئيسي</Link></div></header><div className="grid gap-6 lg:grid-cols-[220px_1fr]"><aside className="dashboard-sidebar rounded-3xl p-4"><nav className="space-y-2"><a className="dashboard-link active"><LayoutDashboard size={17}/> نظرة عامة</a><a className="dashboard-link"><Heart size={17}/> المفضلة</a><a className="dashboard-link"><MessageCircle size={17}/> الرسائل <span className="mr-auto rounded-full bg-[#13c7ae] px-2 py-0.5 text-xs text-white">3</span></a><a className="dashboard-link"><BarChart3 size={17}/> الإحصائيات</a><a className="dashboard-link"><Users size={17}/> العملاء</a><a className="dashboard-link"><Settings size={17}/> الإعدادات</a></nav></aside><section><div className="grid gap-4 sm:grid-cols-3"><div className="stat-card rounded-3xl p-5"><span className="muted-text text-sm">العقارات المنشورة</span><strong>12</strong><small className="teal-text">+3 هذا الشهر</small></div><div className="stat-card rounded-3xl p-5"><span className="muted-text text-sm">إجمالي المشاهدات</span><strong>8,426</strong><small className="teal-text">+18.4%</small></div><div className="stat-card rounded-3xl p-5"><span className="muted-text text-sm">طلبات التواصل</span><strong>34</strong><small className="teal-text">تحتاج متابعة</small></div></div><div className="dashboard-panel mt-6 rounded-3xl p-5"><div className="mb-5 flex items-center justify-between"><div><h2 className="text-xl font-bold">إدارة العقارات</h2><p className="muted-text mt-1 text-sm">آخر الإعلانات والنشاطات على حسابك</p></div><button className="gradient-button flex items-center gap-2 rounded-full px-4 py-2 text-sm font-bold"><Plus size={16}/> إضافة عقار</button></div><div className="space-y-3">{properties.slice(0,3).map((property)=><div key={property.id} className="dashboard-property flex items-center gap-3 rounded-2xl p-3"><img src={property.image} alt="" className="h-16 w-20 rounded-xl object-cover"/><div className="min-w-0 flex-1"><strong className="block truncate">{property.title}</strong><span className="muted-text text-sm">{property.location}</span></div><span className="hidden rounded-full bg-[#13c7ae1c] px-3 py-1 text-xs text-[#1ee8b7] sm:block">نشط</span><span className="font-bold">{property.priceValue.toLocaleString('en-US')} ج.م</span></div>)}</div></div></section></div></div></main>;
}
