import Link from 'next/link';
import { ArrowLeft, BedDouble, Bath, Maximize, MapPin, MessageCircle, CalendarCheck, Heart } from 'lucide-react';
import { properties } from '../../data';
import SiteHeader from '../../components/site-header';
import BookingActions from '../../components/booking-actions';

export default async function PropertyDetails({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const property = properties.find((item) => item.id === id) || properties[0];
  const similar = properties.filter((item) => item.id !== property.id).slice(0, 3);
  return <main className="app-shell min-h-screen px-5 py-8 md:px-10"><div className="mx-auto max-w-7xl"><SiteHeader/><div className="mb-8"><Link href="/search" className="outline-button inline-flex items-center gap-2 rounded-full px-4 py-2 text-sm"><ArrowLeft size={15}/> Back to results</Link></div><div className="property-gallery grid gap-3 md:grid-cols-[1.5fr_1fr] md:grid-rows-2"><img src={property.image} alt={property.title} className="h-full min-h-[360px] w-full rounded-3xl object-cover md:row-span-2"/><div className="hidden rounded-3xl bg-[url('https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=800&q=85')] bg-cover bg-center md:block"/><div className="gallery-placeholder hidden place-items-center rounded-3xl md:grid"><span className="text-center"><Maximize className="mx-auto mb-2"/><small>View all photos</small></span></div></div><div className="mt-8 grid gap-10 lg:grid-cols-[1fr_340px]"><section><div className="teal-text mb-3 text-sm font-bold">{property.operation} · {property.type}</div><h1 className="display-title text-4xl font-bold md:text-5xl">{property.title}</h1><div className="muted-text mt-3 flex items-center gap-2"><MapPin size={17}/>{property.location}</div><div className="property-stats mt-8 grid grid-cols-3 gap-3 rounded-3xl p-5"><span><Maximize/><strong>{property.area} m²</strong><small>Area</small></span><span><BedDouble/><strong>{property.rooms || '—'}</strong><small>Rooms</small></span><span><Bath/><strong>{property.baths || '—'}</strong><small>Bathrooms</small></span></div><h2 className="mt-10 text-2xl font-bold">About this property</h2><p className="muted-text mt-3 max-w-2xl leading-8">{property.description} This property is part of a carefully selected collection created to make your search clear, comfortable, and secure.</p><h2 className="mt-10 text-2xl font-bold">Location on the map</h2><div className="map-placeholder mt-4 grid h-64 place-items-center rounded-3xl"><span className="muted-text">Interactive map integration with Mapbox or Google Maps is ready to be connected.</span></div></section><aside className="contact-card h-fit rounded-3xl p-6"><div className="muted-text text-sm">Price</div><div className="mt-2 text-2xl font-extrabold">{property.price}</div><BookingActions propertyId={property.id} propertyTitle={property.title}/></aside></div><section className="mt-16"><h2 className="display-title text-3xl font-bold">Similar properties</h2><div className="mt-6 grid gap-5 md:grid-cols-3">{similar.map((item)=><Link href={`/property/${item.id}`} key={item.id} className="property-card overflow-hidden rounded-3xl border"><img src={item.image} alt={item.title} className="h-44 w-full object-cover"/><div className="p-4"><h3 className="font-bold">{item.title}</h3><p className="muted-text mt-2 text-sm">{item.location}</p></div></Link>)}</div></section></div></main>;
}
