import { ArrowRight, Bath, BedDouble, FileCheck2, Hammer, LandPlot, MapPin, Maximize, Ruler, ShieldCheck, Sparkles, Trees, Waves } from 'lucide-react';
import Link from 'next/link';
import { properties } from '../../data';
import BookingActions from '../../components/booking-actions';
import SiteHeader from '../../components/site-header';

type DetailMode = 'land' | 'home' | 'stay';
function modeFor(property: typeof properties[number]): DetailMode { if (property.type.toLowerCase().includes('land')) return 'land'; return property.operation === 'For rent' ? 'stay' : 'home'; }
const modeContent = {
  land: { label: 'LAND OPPORTUNITY', eyebrow: 'LAND INTELLIGENCE', title: 'Build the right future on the right ground.', description: 'A focused land profile covering use, access, documentation, and the next decision—not just a beautiful location.', action: 'Request land dossier', alternatives: 'Other land with similar potential', alternativesText: 'Compare nearby plots selected for the same kind of development or investment.', map: 'Area context and access notes', accent: 'detail-land' },
  home: { label: 'OWNERSHIP PROFILE', eyebrow: 'PROPERTY INTELLIGENCE', title: 'A home chosen for how you want to live.', description: 'Explore the spaces, location, and ownership details that make this property worth your next step.', action: 'Arrange a viewing', alternatives: 'Homes with a similar point of view', alternativesText: 'Thoughtful alternatives matched by sale status, property type, and location.', map: 'Neighbourhood and services', accent: 'detail-home' },
  stay: { label: 'STAY PROFILE', eyebrow: 'THE STAY EDIT', title: 'A place that makes the trip feel easy.', description: 'See the space, setting, and essentials before you request the stay that fits your dates and rhythm.', action: 'Request this stay', alternatives: 'Stays for the same kind of escape', alternativesText: 'Similar available stays matched by rental status, type, and destination.', map: 'Nearby places and arrival context', accent: 'detail-stay' },
};
function DetailStat({ icon, value, label }: { icon: React.ReactNode; value: string; label: string }) { return <div className="detail-stat"><span>{icon}</span><strong>{value}</strong><small>{label}</small></div>; }

export default async function PropertyPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const property = properties.find((item) => item.id === id) || properties[0]; const detailMode = modeFor(property); const content = modeContent[detailMode];
  const modeOperation = detailMode === 'land' ? 'land' : property.operation; const similar = properties.filter((item) => item.id !== property.id && modeFor(item) === detailMode && item.operation === modeOperation).slice(0, 3); const fallbackSimilar = properties.filter((item) => item.id !== property.id && modeFor(item) === detailMode).slice(0, 3); const alternatives = similar.length ? similar : fallbackSimilar; const searchMode = detailMode === 'land' ? 'land' : detailMode === 'home' ? 'buy-home' : 'stay'; const isLand = detailMode === 'land'; const isStay = detailMode === 'stay';
  return <main className={`app-shell detail-page ${content.accent} min-h-screen px-5 py-8 md:px-10`}><div className="mx-auto max-w-7xl"><SiteHeader section={isLand ? 'land' : detailMode === 'home' ? 'buy-home' : 'stay'}/><Link href={`/search?mode=${searchMode}`} className="detail-back outline-button inline-flex items-center gap-2 rounded-full px-4 py-2 text-sm">← Back to {isLand ? 'land opportunities' : isStay ? 'stays' : 'homes'}</Link>
    <section className="detail-hero mt-8"><div className="detail-gallery"><img src={property.image} alt={property.title}/><div className="detail-gallery-side"><div className="detail-gallery-secondary" style={{ backgroundImage: `url(${isLand ? 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=900&q=85' : isStay ? 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=900&q=85' : 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=900&q=85'})` }}/><div className="detail-gallery-note"><Sparkles size={20}/><span>{isLand ? 'Opportunity brief' : isStay ? 'Arrival preview' : 'Lifestyle preview'}</span><small>{isLand ? 'Images, access, and documents are reviewed together.' : isStay ? 'See the atmosphere before you request your dates.' : 'See how the space could fit your next chapter.'}</small></div></div></div><div className="detail-intro"><span className="eyebrow">{content.eyebrow}</span><div className="detail-type-badge">{property.operation} · {property.type}</div><h1>{property.title}</h1><div className="detail-location"><MapPin size={17}/>{property.location}</div><p>{content.description}</p></div></section>
    <section className="detail-content-grid"><div><div className="detail-stats">{isLand ? <><DetailStat icon={<LandPlot/>} value={`${property.area} m²`} label="Plot area"/><DetailStat icon={<Ruler/>} value="Road access" label="Access review"/><DetailStat icon={<Trees/>} value="Flexible" label="Use potential"/></> : <><DetailStat icon={<Maximize/>} value={`${property.area} m²`} label="Area"/><DetailStat icon={<BedDouble/>} value={String(property.rooms || '—')} label={isStay ? 'Bedrooms' : 'Rooms'}/><DetailStat icon={<Bath/>} value={String(property.baths || '—')} label="Bathrooms"/></>}</div><article className="detail-story"><span className="eyebrow">{content.label}</span><h2>{isLand ? 'A plot is only valuable when the next move is clear.' : isStay ? 'Everything you need for a better arrival.' : 'The details behind the feeling.'}</h2><p>{property.description}</p></article>{isLand ? <section className="detail-facts"><h2>Land due diligence</h2><div className="detail-fact-grid"><span><ShieldCheck/><strong>Ownership</strong><small>Request the available ownership and title information.</small></span><span><FileCheck2/><strong>Documents</strong><small>Review permitted use and the documents attached to the listing.</small></span><span><Hammer/><strong>Development</strong><small>Discuss access, utilities, and the realistic next use.</small></span></div></section> : <section className="detail-facts"><h2>{isStay ? 'Stay essentials' : 'Why this home works'}</h2><div className="detail-fact-grid"><span><ShieldCheck/><strong>Verified details</strong><small>Clear information before you request the next step.</small></span><span><Waves/><strong>{isStay ? 'Setting' : 'Location'}</strong><small>{isStay ? 'Understand the atmosphere and nearby places.' : 'See the community and services around the property.'}</small></span><span><Sparkles/><strong>{isStay ? 'Comfort' : 'Potential'}</strong><small>{isStay ? 'A considered space for the way you want to stay.' : 'A property with room for the life you are building.'}</small></span></div></section>}<section className="detail-map"><div><span className="eyebrow">LOCATION CONTEXT</span><h2>{content.map}</h2><p>The map view will be connected to a provider when the location service is configured. For now, the listed area is shown clearly without inventing an exact address.</p></div><div className="map-placeholder"><MapPin size={24}/><span>{property.location}</span></div></section></div><aside className="detail-action-card"><span className="eyebrow">YOUR NEXT STEP</span><h2>{content.action}</h2><div className="detail-price-label">{isLand ? 'Investment guide price' : isStay ? 'From per night' : 'Asking price'}</div><strong className="detail-price">{property.price}</strong><BookingActions propertyId={property.id} propertyTitle={property.title} variant={detailMode}/></aside></section>
    <section className="detail-alternatives"><div className="detail-alternatives-heading"><div><span className="eyebrow">SMART MATCHES</span><h2>{content.alternatives}</h2><p>{content.alternativesText}</p></div><Link href={`/search?mode=${searchMode}`} className="outline-button inline-flex items-center gap-2 rounded-full px-4 py-2 text-sm">See all <ArrowRight size={15}/></Link></div>{alternatives.length ? <div className="smart-match-grid">{alternatives.map((item) => <Link href={`/property/${item.id}`} className="smart-match-card" key={item.id}><div className="smart-match-image" style={{ backgroundImage: `linear-gradient(0deg,rgba(3,18,31,.9),rgba(3,18,31,0) 72%),url(${item.image})` }}><span>{item.operation} · {item.type}</span><ArrowRight size={18}/></div><div><strong>{item.title}</strong><small><MapPin size={13}/>{item.location}</small><em>{item.price}</em><p>{item.description.slice(0, 92)}…</p></div></Link>)}</div> : <div className="empty-state">No close alternatives are available yet. Browse the full collection to find another fit.</div>}</section>
  </div></main>;
}
